### ISSUE TITLE
Archiver needs to have its own CSS

### ISSUE THREAD

**Issue by fdemello** [CiscoDevNet/webex-teams-archiver#2]
The archiver currently [links](https://github.com/CiscoDevNet/webex-teams-archiver/blob/25ef9c19b2d2736c1ce0e1f190e76238b019ce2e/webexteamsarchiver/templates/header.html#L7) to the Webex Teams CSS because we were not able to license the CSS to be included in this project. This creates a few problems:

- When the Webex Teams CSS changes, [and it changes quite frequently](https://github.com/CiscoDevNet/webex-teams-archiver/commits/master/docs/teams.css), it may break current archives.
- It prevents the archive from being a true offline copy.
- It may require changes to the jinja templates.
- It requires updating [teams.css](https://github.com/CiscoDevNet/webex-teams-archiver/blob/master/docs/teams.css), although this process is currently automated.

Developing our own CSS, even a very simple one, would solve all of these problems. 

Requirements:

- The CSS should try to mimic, as much as possible, the look and feel of Webex Teams web.
- It should contain classes that cover special classes used in Webex Teams messages (e.g. spark-mention).

**Comment by jbogarin** [comment]
Felipe,

If you don't mind and nobody else is interested in this, I'll work on it with @EvelynBarquero

I think we can have a first draft in one or two weeks.

Let me know if you have any other requirements or ideas around this.

**Comment by fdemello** [comment]
@jbogarin Nobody else has volunteered so I'm more than happy to accept the offer to help :). My only ask is that we try to maintain a similar layout without copying Webex Teams CSS in order to avoid any license violations. If there are open source CSS libraries out there (e.g. bootstrap, Cisco UI kit?) that could be used to facilitate, I think we should use them.

If you don't mind, I would like to create a space with the three of us so that we can discuss anything that comes up during the design.

Thanks!

**Comment by jbogarin** [comment]
Sounds great.

**Comment by fdemello** [comment]
https://github.com/CiscoDevNet/webex-teams-archiver/pull/13
