### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by turc42** [CiscoDevNet/webex-teams-archiver#20]
MarkupSafe has removed soft_unicode 

https://markupsafe.palletsprojects.com/en/2.1.x/changes/

This issue is easily addressed by setting the version in requirements.txt file to the previous version. 

MarkupSafe==2.0.1

[requirements.txt](https://github.com/CiscoDevNet/webex-teams-archiver/files/8173054/requirements.txt)

[error.txt](https://github.com/CiscoDevNet/webex-teams-archiver/files/8173066/error.txt)

**Comment by fdemello** [comment]
Fixed in v0.11.3.
